### PR TITLE
Seeding goref YAML/MDs

### PR DESCRIPTION
**Pull request by cmungall**
See #214

### CODE REVIEW

**Comment by cmungall** [comment]
This is how it looks: https://github.com/geneontology/go-site/blob/issue-214/metadata/gorefs/goref-0000002.md

A bit ugly, but we could easily pandocify in advance of jekyll or render any number of ways

**Comment by cmungall** [comment]
@kltm ok to merge?

**Comment by kltm** [comment]
Checks failed?

**Comment by kltm** [comment]
@cmungall still failing.

**Comment by cmungall** [comment]
time to switch to https://pypi.python.org/pypi/pykwalify

**Comment by kltm** [comment]
You'll have to run that through virtualenv.

**Comment by kltm** [comment]
@cmungall The failure
```
The command "./scripts/combine-datasets-metadata.py metadata/datasets/*.yaml > metadata/datasets.json" exited with 127.
```
would seem to be unrelated?

**Comment by cmungall** [comment]
Not following. The error is due to a lack of python3 in the ruby build environment. Would virtualenv make it easier to combine the? Seems more straightforward to just go for a straight python environment, it's what we use for most travis jobs.

**Comment by kltm** [comment]
IIRC, the "build environment" in Travis is just the base image and some var/env stuff over a pretty vanilla Ubuntu image. You can install any package you want and run any command within that environment, including python3. (I think that's right, last time I checked something like this in detail was in the GitLab CI docs, so a shout-out there, but a quick look at the Travis docs seems to agree.)
Of course, python3 is not standard in base Ubuntu, so it must be installed separately and referred to explicitly over the default python2. As well, pykwalify is just (apparently) a random library and not packaged in any standard location, so must be installed separately either with pip directly or using virtualenv locally--a bit of an irritation. 
As far as the current job goes, it does not necessarily need to be the ruby image, that's just the way I started with it--there are other ways to skin that cat.
The reason I default to kwalify is not any deep love, but that it is a standard package in Ubuntu, making upgrading, security, etc. easy for our systems; the Travis CI is just an extension of that standardization, but can be changed as their VMs are throw-away.

**Pull request merged**
