### PR TITLE
Pipeline issue 206 downloader update

### PR DESCRIPTION
**Pull request by dougli1sqrd**
smart downloading!

new command called `annotations` that uses either gaf, or gpad+gpi.

for https://github.com/geneontology/pipeline/issues/206

### CODE REVIEW

**Comment by kltm** [comment]
@dougli1sqrd It's looking good.

Keeping in the spirit of "locally executable atomic parts running in order", would you mind adding a README with a few examples of usage and the expected inputs and outputs?

**Comment by dougli1sqrd** [comment]
Sure. Where should the readme live? Or which readme should I add to?

**Comment by dougli1sqrd** [comment]
I also have concerns about the name of the script referring to GAF still, rather than something more generic. But if we renamed it we'd have to change the invocations too

**Comment by kltm** [comment]
Changing invocations I think is fine to keep things clear. We're ripping up the floorboards here anyways, so why not?
For a README, either in the main one in scripts, or README.script_name.

**Comment by dougli1sqrd** [comment]
okay @kltm, added some examples for downloader script readme

**Comment by kltm** [comment]
Given that this is hung up on docker/travis issues, please go ahead and merge. Also see https://github.com/geneontology/go-site/issues/1590

**Pull request merged**
