### PR TITLE
Update gorule-0000064.md

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by mugitty** [comment]
@pgaudet, please add some test cases to the error GAF file.

**Comment by kltm** [comment]
(All PRs should have a ticket and all tickets should have a project.)

**Comment by pgaudet** [comment]
??? 
https://github.com/geneontology/go-site/issues/2273

PRs are linked.... 


what's not working ?

**Comment by kltm** [comment]
Linked now!

**Pull request merged**
