### PR TITLE
Update users.yaml

### PR DESCRIPTION
**Pull request by suzialeksander**
New user from https://github.com/geneontology/helpdesk/issues/291

User did not indicate an interest in using Noctua

### CODE REVIEW

**Comment by kltm** [comment]
@suzialeksander I'm guessing that that groups is not in groups.yaml, or badly formed?

**Comment by kltm** [comment]
@suzialeksander I'm also not sure if groups or authorizations are necessary or desired here, as they do not seem to be sponsored to work with Noctua?

**Comment by suzialeksander** [comment]
Correct, I did not give them edit permissions in Noctua.  It's a new group, I did attempt to add to groups.yaml but I was unsure about that too.

**Comment by kltm** [comment]
Okay, since they are not Noctua, I'm pulling the authorizations and groups.

**Pull request closed without merging**
