### PR TITLE
For #2210

### PR DESCRIPTION
**Pull request by mugitty**
Fixed panther id syntax pattern

### CODE REVIEW

**Comment by mugitty** [comment]
Tagging @alexsign

**Comment by mugitty** [comment]
@dustine32, Please review.  It is [linked ](https://github.com/biolink/ontobio/tree/go-site-2210-gorule-0000027-must-check-dbs-are-in-the-db-xref-file)

**Review by dustine32 — APPROVED** [review]
@mugitty From what I can tell, this change should be fine to merge. Just curious, is there any test annotation in `scripts/rule-example-validation.sh` that would check this pattern?

**Comment by mugitty** [comment]
I found it in https://github.com/geneontology/go-site/blob/master/docs/gorules_test_errors.gaf,
...
UniProtKB	A0A140VJL9	A0A140VJL9	involved_in	GO:0006783	GO_REF:0000118	IEA	PANTHER:PTHR11458:SF0	P	GORULE_TEST:0000064-1		protein	taxon:9606	20240201	TreeGrafter	
...
This line is supposed to test Gorule 64. However, the syntax pattern test, flagged PANTHER:PTHR11458:SF0 as well

**Comment by dustine32** [comment]
@mugitty Cool, thanks! As long as you can observe a difference ("PANTHER:PTHR11458:SF0" is flagged) that should work as a test.

**Pull request merged**
