### PR TITLE
gaferencer now wrapped in a script that handles the metadata and the …

### PR DESCRIPTION
**Pull request by dougli1sqrd**
…group orientation

I'm going to make a pipeline test branch to run this. It'll be the same as master but I'll add pamgo.

### CODE REVIEW

**Comment by kltm** [comment]
@dougli1sqrd I'll work on a doc to go over some common patterns, etc., that we'll use.
For now, would you mind re-tuning this with Ubuntu Minimal LTS (18.04)? (https://wiki.ubuntu.com/Minimal)

**Comment by dougli1sqrd** [comment]
It looks like the 18.04 docker image is already the minimal release? https://ubuntu.com/blog/minimal-ubuntu-released

**Comment by dougli1sqrd** [comment]
Also I can contribute to the doc, as I've contributed to my fair share of wonky things in the pipeline

**Comment by kltm** [comment]
Confirming that I was wrong about the ubuntu image--it is the minimal one.
Noting that default python3 in bionic is 3.6.5-3.
I cannot find the maven dependency you reported for java 11. What you seem to be seeing is the `openjdk-11-jre-headless` being brought in by `default-jre-headless`, which is harmless. If we are deciding on open-jdk-8, the additional command you want after something like:
```
apt-get -u install python3 openjdk-8-jre maven
```
is
```
update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
```
giving us:
```bash
root@fcf40db5371b:/# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```

**Comment by dougli1sqrd** [comment]
Won't merge.

**Pull request closed without merging**
