### PR TITLE
Add script to convert YAML files to Turtle.

### PR DESCRIPTION
**Pull request by balhoff**
This script can be used to support production of users and groups ttl files for #469.

### CODE REVIEW

**Comment by kltm** [comment]
@balhoff 
What is the `riot` command here?

**Comment by balhoff** [comment]
Part of Jena command line tools.

**Comment by balhoff** [comment]
I just pushed a fix for a misuse of the tmpfile variable.

**Comment by kltm** [comment]
Okay, we'll have to figure out a way of getting Jena onto all the machines then. Either that, or add it to the "software" steps of the build.

**Comment by balhoff** [comment]
Yep, either that or instead the ruby packages for the approach in https://github.com/geneontology/go-site/pull/442#issuecomment-335249178

**Pull request merged**
