### PR TITLE
Update reactome.yaml

### PR DESCRIPTION
**Pull request by vanaukenk**
Updating source file location
@dougli1sqrd - please double-check and make sure everything is okay.  Thx.

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
This 404s actually https://www.reactome.org/download/current/gene_association.reactome.gz

**Comment by kltm** [comment]
I would note that currently nothing like that seems to exist in https://www.reactome.org/download/current/

**Comment by ukemi** [comment]
It is there on their downloads page, but not as a zipped file.

**Comment by vanaukenk** [comment]
Ah - I think I misunderstood Joel's email.
This file *will* be available with the next Reactome release, 68.
I'll confirm with Joel about when this will be available and then we can merge the pull request.

**Comment by vanaukenk** [comment]
Next Reactome release date: ~March 20th

**Comment by vanaukenk** [comment]
The new Reactome release is available, so the annotation file is now on their site.

I'm going to go ahead and merge the pull request.

**Pull request merged**
