### PR TITLE
Issue 2281 only implemented rules in reports

### PR DESCRIPTION
**Pull request by mugitty**
Output information in reports only for rules that have been implemented

### CODE REVIEW

**Comment by kltm** [comment]
@mugitty I just want to confirm a bit of overall logic: rules that have been implemented elsewhere (i.e. not ontobio), are still "implemented", but would not appear in the reports from ontobio, but may appear in other reports and may be merged into the main reports some other way. Naturally, no un-implemented things should appear in any reports, but implemented things not in ontobio may.

**Comment by mugitty** [comment]
@kltm, do we want ontobio to check if the status of the rule is approved or implemented?

**Comment by mugitty** [comment]
The MODS use the reports to check for errors. @pgaudet did not want errors to be displayed before the functionality for the checks was implemented

**Comment by kltm** [comment]
@mugitty Again, that's all fine. I just want to be clear on GORULEs not being strictly limited to ontobio. This all seems fine within the expected scope.

**Review by kltm — APPROVED** [review]
Simple changes to filter ontobio-local rules.

**Comment by pgaudet** [comment]
Hi @kltm 

Thanks for the feedback. In fact I had asked Eric to have the information of 'where are rules implemented' avialable in the GORULEs info - . I think that corresponds to "implementations" in the [schema](https://github.com/geneontology/go-site/blob/master/metadata/rules.schema.yaml) . Values here should be an enum. 

This information would be very useful.

**Pull request merged**
