### PR TITLE
use go_reports.py to generate all stats & diff files

### PR DESCRIPTION
**Pull request by lpalbou**
@kltm  here is the command line to generate all the stats & reports files:

```
python3 go_reports.py -g http://golr-aux.geneontology.io/solr/ -c http://current.geneontology.org/ontology/go.obo -p http://release.geneontology.org/2019-06-09/ontology/go.obo -s https://geneontology.s3.amazonaws.com/archive/2019-06-09_go-stats.json -o reports
```

Notes:
* -c is for the current obo url
* -p is for the previous obo url
* -s is for the previously calculated stats (I use the june version to compute the current diffs but for next month, you can use this one: https://geneontology.s3.amazonaws.com/go-stats.json
* -o is the output folder where all the files will be generated

7 files generated:
* [go-stats.json](https://geneontology.s3.amazonaws.com/go-stats.json)
* [go-stats.tsv](https://geneontology.s3.amazonaws.com/go-stats.tsv)
* [go-meta.json](https://geneontology.s3.amazonaws.com/go-meta.json)
* [go-ontology-changes.json](https://geneontology.s3.amazonaws.com/go-ontology-changes.json)
* [go-ontology-changes.tsv](https://geneontology.s3.amazonaws.com/go-ontology-changes.tsv)
* [go-annotation-changes.json](https://geneontology.s3.amazonaws.com/go-annotation-changes.json)
* [go-annotation-changes.tsv](https://geneontology.s3.amazonaws.com/go-annotation-changes.tsv)

### CODE REVIEW

**Comment by kltm** [comment]
@lpalbou Looks like there are conflicts.

**Comment by lpalbou** [comment]
Strange but corrected

**Comment by kltm** [comment]
I don't quite understand what is going on here. There should be two files/data (or sets): one for the current release and one in comparison to the "previous" (defined by what is at `current`). There seems to be more mechanism going on here.

Could you sketch out what you are wanting with the current command used as an example? https://github.com/geneontology/pipeline/blob/master/Jenkinsfile#L844

**Comment by lpalbou** [comment]
@kltm there are some new requirements to compute stats and diffs (see the above explanations and google doc of the project for the files to be generated). You now have to specify a new parameter (-n) that must point to the stats computed without direct annotations to protein binding terms.

The command line that I gave above works fine and I have used it to generate those files. Please update your pipeline with the last commit as you are still using the very first version of that script and I am not even seeing the go-annotation-changes or go-ontology-changes on http://skyhook.berkeleybop.org/release/metadata .

**Comment by lpalbou** [comment]
This is the last version used to assess the content of the September release.

Command is the same but as the stats format changed a little bit, please use these new URLs for the previous stats:

```
python3 go_reports.py -g <full_golr_url> -s https://geneontology.s3.amazonaws.com/temporary/2019-july/go-stats.json -n https://geneontology.s3.amazonaws.com/temporary/2019-july/go-stats-no-pb.json  -c <current_obo_release_url> -p https://geneontology.s3.amazonaws.com/archive/2019-07-01_go.obo -o release_stats/
```

And just to be clear:
* <full_golr_url> should be the http:// of the golr with the new release 
* <current_obo_release_url> should be the http:// of the go.obo of the new release (e.g.  http://skyhook.berkeleybop.org/snapshot/ontology/go.obo )

**Comment by lpalbou** [comment]
Added a -d <release_date> parameter (e.g. -d 2019-09-01 for the new release).

Above command updated with -d:
```
python3 go_reports.py -g <full_golr_url> -s https://geneontology.s3.amazonaws.com/temporary/2019-july/go-stats.json -n https://geneontology.s3.amazonaws.com/temporary/2019-july/go-stats-no-pb.json  -c <current_obo_release_url> -p https://geneontology.s3.amazonaws.com/archive/2019-07-01_go.obo -o release_stats/ -d 2019-09-01
```

Notes:
* This script was originally used whenever the pipeline has deployed a new release. The release date was then taken from current.geneontology.org/meta/release_date.json.
* To run within the pipeline prior to the release, we then need to specify the `release_date` of the release to be deployed (there is no information in GOLr about the date and OBO file date differs)

**Comment by lpalbou** [comment]
@kltm I suppose we can close this PR without merging since we push the changes in https://github.com/geneontology/go-site/pull/1181 ?

**Comment by kltm** [comment]
Ah, yes--the changes should be the same as `issue-842-add-stats`.

**Pull request closed without merging**
