### PR TITLE
update wording in gorule-33

### PR DESCRIPTION
**Pull request by dougli1sqrd**
See https://github.com/geneontology/go-site/issues/1082

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
also, @cmungall can we change the rule to `approved` or `implemented`? Right now it's still proposed.

**Comment by pgaudet** [comment]
Sorry @dougli1sqrd I accidentally changed the status to 'approved' directly into master. (I should go to bed ;)

**Comment by dougli1sqrd** [comment]
This is implemented here: https://github.com/biolink/ontobio/pull/327

**Comment by kltm** [comment]
I would think that "should be preferred" is a little weaker than the "will be filtered" rule that it is...

**Comment by dougli1sqrd** [comment]
Well since this is mostly a report, and a repair only if we can, I worded it more gently. Since we won't filter out "bad" references.

**Comment by vanaukenk** [comment]
This rule is part of the GPAD 2.0 specifications, but I didn't know that we were starting to implement it now.
We should probably discuss on an annotation call to give people more notice.

**Comment by dougli1sqrd** [comment]
Yeah, discussing it on the next call is fair. We can at least merge these changes to this rule if we agree with the wording, and not update the pipeline to the latest ontobio so the changes don't actually get activated until we're ready? @kltm does that or something similar sound like an okay way to go?

**Comment by kltm** [comment]
@dougli1sqrd I would actually defer merging until we were ready (as that may end up blocking other things in the interim).
Make sure the PR is tied to a ticket and we can revisit.

**Comment by kltm** [comment]
@pgaudet @vanaukenk If data is being changed for our downstream bulk consumers (as opposed to "direct" AmiGO users) and it is not a critical "damage" fix, perhaps they could be introduced first as a warning/report and then graduate to mutation/filtering once there was a cool-off period (1m? 3m?)?

**Comment by dougli1sqrd** [comment]
I updated the PR to just report, and changed the ontobio PR implementation here: https://github.com/biolink/ontobio/pull/328 to just WARN also

**Pull request merged**
