### PR TITLE
Update requirements.txt for #844

### PR DESCRIPTION
**Pull request by mugitty**
Bringing in changes from https://github.com/biolink/ontobio/pull/632

Will test on Jenkins test branch

### CODE REVIEW

**Comment by kltm** [comment]
@mugitty This is a trivial change, so merge at will.

**Review by kltm — APPROVED** [review]

**Comment by kltm** [comment]
@mugitty @dustine32 It looks like your pipeline has failed. Odd error in the reports. Are you up-to-date with `master`/`snapshot`?

**Comment by mugitty** [comment]
Jenkins file got to be large, so I temporarily removed part of the publishing step.  This may have caused the problem. I need to look in detail

**Comment by kltm** [comment]
@mugitty Importantly, "Publishing" and "Archiving" should be either kept intact or removed entirely--having a partial publish step could cause problems, such as overwriting live data with bad data.
That said, it was in reports where it failed, so I'd doubt the error was there.

**Comment by mugitty** [comment]
It failed while comparing stats from previous to current release. Specifically, it cannot find 'process' aspect items in the json file.

**Comment by dustine32** [comment]
https://github.com/geneontology/go-site/pull/2004/commits/65b1bdff8366bd84e4bc8c9967568870655e3675 is for fixing `pip install ../graphstore/rule-runner` [errors](https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-go-site-844-ext-repair-obs/18/execution/node/375/log/):
```
20:00:22  Collecting SPARQLWrapper==1.8.0
20:00:22    Downloading SPARQLWrapper-1.8.0.zip (36 kB)
20:00:22    Preparing metadata (setup.py): started
20:00:22    Preparing metadata (setup.py): finished with status 'error'
20:00:22    error: subprocess-exited-with-error
20:00:22    
20:00:22    × python setup.py egg_info did not run successfully.
20:00:22    │ exit code: 1
20:00:22    ╰─> [1 lines of output]
20:00:22        error in SPARQLWrapper setup command: use_2to3 is invalid.
20:00:22        [end of output]
```
Also another error installing `pyYaml==5.4.1`:
```
        (a long, long stack trace and then...)
        File "/private/var/folders/mn/4r4wdgk16z7cvnq3t2zrhkf40000gp/T/pip-build-env-dvoojr4k/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/mn/4r4wdgk16z7cvnq3t2zrhkf40000gp/T/pip-build-env-dvoojr4k/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/mn/4r4wdgk16z7cvnq3t2zrhkf40000gp/T/pip-build-env-dvoojr4k/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
```
We'll see in testing how this affects the GO pipeline build and whether we need to pin to any specific versions.

**Review by dustine32 — APPROVED** [review]
@mugitty and I sorted out the python3.10 upgrade bugs on this branch as we saw them pop up on the Jenkins build pipeline. A lot of unpinning dependencies.

Hopefully this is everything we need to do. But if there are more, newly discovered bugs we can just continue to fight through them.

**Pull request merged**
