### PR TITLE
File extensions

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by kltm** [comment]
@dougli1sqrd does this produce ttl and ttl.gz? Once produced, will blazegraph loading be able to operate just from ttl.gz?

**Comment by dougli1sqrd** [comment]
@kltm yeah I had this keep the ttls around, cause that's what blazegraph and other targets use. Otherwise I have to do the zip/unzip business that we already do with the gaf artifacts.

**Comment by kltm** [comment]
From the skype commentary, it looks like we might want to change blaze-runner to accept gzipped TTLs.

**Comment by kltm** [comment]
From more skype commentary, and in-person convo, probably not right now.

**Pull request merged**
