### PR TITLE
removing owltools reports from merged group reports

### PR DESCRIPTION
**Pull request by dougli1sqrd**
For https://github.com/geneontology/go-site/issues/1386

Removing owltools reports in merged html file. The reports themselves will still be produced and still live, this just modifies how the reports are displayed in html.

As an aside, we should be aware of the version of the python `markdown` library. Current is 3.2.1, wherein the `markdown.extension.headerid` extension is deprecated. Our current version works, but we should consider changing how we produce the markdown -> html and update this extension to one that isn't deprecated, and then upgrade the markdown package.

### CODE REVIEW

**Comment by kltm** [comment]
Removal of report and summary?

**Comment by dougli1sqrd** [comment]
Yeah. I will still make a pipeline branch of this and run it, just so we see it w/out disruption first.

**Comment by kltm** [comment]
Okay, sounds good.

**Comment by dougli1sqrd** [comment]
Running in pipeline from a branch here: https://github.com/geneontology/pipeline/tree/issue-1386-remove-owltools-report

**Pull request merged**
