### PR TITLE
Delete gonuts.yaml

### PR DESCRIPTION
**Pull request by kltm**
#1078

### CODE REVIEW

**Comment by kltm** [comment]
@dougli1sqrd Any hard-codings for gonuts that would cause the pipeline to break?

**Comment by kltm** [comment]
Does not seem to be loaded into AmiGO, so no change needed there.

**Comment by dougli1sqrd** [comment]
No it should be fine. The only real place to look is if we are using it in the master Pipeline run as a test (I'm pretty sure we're not)

**Comment by dougli1sqrd** [comment]
Indeed, I have double checked, and we are not.

**Comment by kltm** [comment]
Cheers!

**Pull request merged**
