### PR TITLE
Changed schema to express deprecated resources

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by pgaudet** [comment]
@kltm does this work to capture deprecated resources, ie adding to the schema: 
is_obsolete: boolean

**Comment by kltm** [comment]
Obsolete in what context? Again, we are not the only ones that use this file. If a resource no longer has a usable CURIE -> URL/website map and it cannot be fixed, it should just be removed.

**Comment by pgaudet** [comment]
OK - I was doing what @cmungall had suggested in the comments, but I also think it's cleaner if we remove the sources completely.

**Comment by kltm** [comment]
I agree here, but if the mapping is legit I see no reason not to leave them.

**Comment by pgaudet** [comment]
> I agree here, but if the mapping is legit I see no reason not to leave them.

Of course - when I say obsolete it means the URL is dead and I can find no new link to replace it. Most of the cases we know the resource is not maintained and its data not available anywhere. 

Should I add this 'obsolete' tag in the schema ? Or just delete the resource ?

**Comment by kltm** [comment]
You should absolutely delete it: there is no utility in a mapping that doesn’t work.

**Pull request closed without merging**
