### PR TITLE
Update GO annotations for L. major and T. brucei

### PR DESCRIPTION
**Pull request by Achchuthan**
Source URLs have been changed for these two organisms and you can pull the data for these from the respective ftp links.

### CODE REVIEW

**Comment by kltm** [comment]
@dougli1sqrd 
I'm wondering about the combination of the "compression" field and the lack of compression and suffix in the PR?

**Comment by dougli1sqrd** [comment]
Oh yes, this should probably be gzipped. We don't currently support non gzip formats. That's something we could support in the future though.

**Comment by Achchuthan** [comment]
Hi @kltm, @dougli1sqrd , 

Sorry for the inconvenience. 
Do you want me to make the re-submission with gzipped files and commit it again?
I have the gzipped versions deposited in the FTP site.
ftp://ftp.sanger.ac.uk/pub/project/pathogens/as44/Tbruceibrucei927.gaf.gz
ftp://ftp.sanger.ac.uk/pub/project/pathogens/as44/Lmajor.gaf.gz

Thanks,
Achchuthan

**Comment by dougli1sqrd** [comment]
Hi, @Achchuthan, yeah, just update the respective `source` fields with your two gzip URLs. As long as we can download a gzip, it should all be good!

**Comment by kltm** [comment]
Assuming fixed in #665

**Pull request closed without merging**
