### PR TITLE
Explain where PAINT annotations are located.

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by kltm** [comment]
Also note that this will seriously change with https://github.com/geneontology/go-site/issues/642

**Comment by cmungall** [comment]
This metadata file is currently used by the GO Central pipeline. Without it, the pipeline has no way of knowing where to fetch PAINT files from.

**Comment by pgaudet** [comment]
Are you talking about the files that the 'Pipeline' loads, or how MODs should pick up their PAINT data ? This ticket was about the latter; I dont know if our response addresses that.

**Comment by kltm** [comment]
@pgaudet This PR would shut down a critical part of the pipeline line. Unless this PR contains an alternate to the current pipeline, this cannot be accepted.

**Comment by kltm** [comment]
@pgaudet "...This ticket was about the latter..."
You are not in the ticket/issue section, this is the PR (pull request) area and the change that you are trying to commit would severely adversely affect the current running of the pipeline.

**Comment by pgaudet** [comment]
ok good thanks !

**Pull request closed without merging**
