### PR TITLE
changing the wording of gorule 33, and deprecating

### PR DESCRIPTION
**Pull request by dougli1sqrd**
For https://github.com/geneontology/go-site/issues/1082

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
@pgaudet Here's the rewording that we discussed at the meeting. Let me know what you think?

**Comment by kltm** [comment]
Pening discussion on https://github.com/geneontology/go-site/issues/1082

**Comment by dougli1sqrd** [comment]
@pgaudet says we will deprecate this rule: #1082 (comment)
> After discussion with @ukemi and @vanaukenk
> We will deprecate this rule. Groups want to link to their internal pages for all references.

**Comment by pgaudet** [comment]
@dougli1sqrd Can we look at this together ?

**Comment by dougli1sqrd** [comment]
@pgaudet we can look at it together if you would like. But is my understanding wrong then when you said in the comment linked to above, that you and @vanaukenk and @ukemi have decided this rule should be deprecated? My thought was that we would then set the rule to be deprecated in the yaml, and turn off the processing of this rule.

**Comment by pgaudet** [comment]
OK yes sure, if all you did is deprecate and inactivate the rule, then please merge. 
Thanks ! Pascale

**Pull request merged**
