### PR TITLE
added PROQUEST stanza for dissertation referencing

### PR DESCRIPTION
**Pull request by austinmeier**
Added DBX ref stanza for Proquest to point to thesis and dissertations.

### CODE REVIEW

**Comment by kltm** [comment]
Any comment here @cmungall ?

**Comment by cmungall** [comment]
guess it's OK but in these cases I'd just use the URL directly in PO

**Comment by kltm** [comment]
@austinmeier thoughts?

**Comment by austinmeier** [comment]
Proquest holds records for other thesis and dissertations that might be helpful in the future.  I'm okay just using the URL as well. 

Request for this reference: https://github.com/Planteome/go-site-xrefs-fork/issues/1

**Comment by austinmeier** [comment]
We will use the URL (until a need to add proquest database arises again!)

**Comment by cooperl09** [comment]
We could use he URL in this case. If we get more refs from this source, we can revisit.

**Pull request closed without merging**
