### PR TITLE
hopefully this wont summon cthulu, but this changes the makemaker to …

### PR DESCRIPTION
**Pull request by dougli1sqrd**
…generate targets for noiea goa_uniprot_all

### CODE REVIEW

**Comment by kltm** [comment]
I suspect this will either break or fall through the sanity checks, but it's probably to get this worked out early in the month.

**Comment by dougli1sqrd** [comment]
Oh maybe. It seems like it's a super set of what we were doing before. As in, we just do extra processing on the noiea, and other downstream stuff won't know the difference? Maybe? haha, Whatever I can do to help.

**Comment by kltm** [comment]
Discussed with @dougli1sqrd . He'll do some testing with the sanity scripts and get a version working with the `iteration` branch.

**Comment by dougli1sqrd** [comment]
Looking over your sanity script, I anticipate fewer problems than maybe you thought? But only experiment will show...

**Pull request merged**
