### PR TITLE
Added example for gorule-0000006

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by pgaudet** [comment]
@dougli1sqrd @kltm Do you know why this is failing ?

**Comment by kltm** [comment]
It looks like fundamental GAF parsing issues.
I'm guessing that you're using a symbol when you should be using an ID?

**Comment by kltm** [comment]
Or count the number of fields again?

**Comment by kltm** [comment]
Okay, it looks like you're missing the `with/from`--everything gets bumped back by one and the wheels fly off the unprotected parser.
I would suggest that you go ahead and make a "GAF template" in a spreadsheet, fill it in there, then export as TSV to drop in to these examples.

**Comment by pgaudet** [comment]
@kltm I don't understand the error message ""success": false,

            "reason": "Input was expected to fail gorule-0000006, but it did not: extensions should be relation(curie)"" 

???

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Your fail line did not fail as expected.

**Comment by pgaudet** [comment]
Yayyyyyyy !!!!

**Pull request merged**
