### PR TITLE
GO_REF yamldown parser

### PR DESCRIPTION
**Pull request by sujaypatil96**
In this PR we seek write a parser for the GO_REFs such that it can parse through each of the current gorefs and produce equivalent YAML for them in a single consolidated YAML.

To run the parser:

```
python scripts/goref_parser/parser.py
```

In the root of your project, a file called `gorefs.yaml` will be outputted.

CC: @kltm @sierra-moxon @cmungall

### CODE REVIEW

**Comment by sujaypatil96** [comment]
I think this PR is ready for review @kltm.

**Comment by kltm** [comment]
This looks good!
I think it would be good to split the code and data changes into separate PRs, especially as we cannot go forward with the data merge into `master` until the rest of the checklist is completed.

**Comment by kltm** [comment]
#1764

**Review by kltm — CHANGES_REQUESTED** [review]
This looks good!
I think it would be good to split the code and data changes into separate PRs, especially as we cannot go forward with the data merge into master until the rest of the checklist is completed.
The code, as it's standalone, could go in immediately.
https://github.com/geneontology/go-site/issues/1764#issue-1107537863

**Review by kltm — COMMENTED** [review]
Looks good. I'd be happy to merge (or review) depending on what you'd like.
Are there python version restrictions or other requirements for running this? As you have your own directory, you could add anything you'd like to note or need there.
Otherwise, I'll pass the review and merge.

**Review by kltm — APPROVED** [review]

**Comment by sujaypatil96** [comment]
@kltm: I verified, and the script runs properly on versions 3.7 onwards. I've also frozen out a requirements.txt file.

**Pull request merged**
