### PR TITLE
Created new gorule-0000039

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by kltm** [comment]
How is the protein complex identified in this case?

Rule needs a description for implementation.

**Comment by kltm** [comment]
C2 is the local identifier, how would that be identified? Is this to check the namespace in c1?

**Comment by pgaudet** [comment]
@kltm Yes 

What is the namespace for the Complex Portal ? (where do we store these?)

**Comment by pgaudet** [comment]
Is this now accurate ?

**Pull request merged**
