### PR TITLE
Update goref-0000115.md

### PR DESCRIPTION
**Pull request by hattrill**
add FlyBase xref

### CODE REVIEW

**Comment by pgaudet** [comment]
@kltm why is this failing ?

**Comment by kltm** [comment]
@pgaudet That's a "symbol", not a CURIE identifier. Everything must bring along its full context.

**Review by hattrill — COMMENTED** [review]
Have add FB: prefix
What should I do next?

**Comment by kltm** [comment]
It's passing now! @pgaudet knows more context here, so it might be better for here to merge.

**Pull request merged**
