### PR TITLE
adding gorule-0000059 text

### PR DESCRIPTION
**Pull request by dougli1sqrd**
For https://github.com/geneontology/go-site/issues/1558

### CODE REVIEW

**Comment by kltm** [comment]
@dougli1sqrd Looks fine for a first pass. To keep things quick, merge PR on pass.

**Comment by dougli1sqrd** [comment]
Hi @pgaudet, can you verify you're okay with the gorule-0000059 text as written here?

This is for https://github.com/geneontology/go-site/pull/1616

This has been merged already because we need it for GAF 2.2. But as far as the specific wording, etc, can you look it over? If there's anything to change we can make a ticket to update the specifics, thanks!

**Comment by pgaudet** [comment]
- Isn't that GAF2.2 ? 
- Maybe instead of "This is due to the other annotation formats having a richer set of Relations available to them. In order to interoperate between GAF 2.1 and other formats as other formats have a richer set of allowed relations, this will be a process to provide basic compatibility." , we can start the text of rule with "The GAF2.2 format requires an annotation relation in the qualifier field (column 4). " (and then continue with "When processing..." 
OK ? 

@vanaukenk 
-

**Comment by pgaudet** [comment]
ALSO 

rule is 'implemented', not 'proposed'

**Pull request merged**
