### PR TITLE
Update users.yaml

### PR DESCRIPTION
**Pull request by tberardini**
Added ORCID for Donghui.

### CODE REVIEW

**Comment by cmungall** [comment]
Not sure we need the comment field but does no harm

**Comment by kltm** [comment]
Probably copying the legacy of the comment field containing the orcid--there's a lot of that still in there.

**Comment by tberardini** [comment]
Yup, I just copied what was in my record over.

**Comment by kltm** [comment]
No harm, but like @cmungall sez, not necessary anymore. In a previous version of this data, before it all got merged together, the orcid was kept in the comment field when available. After all the different sources were merged into this new single format, since a lot of people seemed to be using the comment field for different things, we just left it alone. This leads to a little replication, but not a big deal.

**Pull request merged**
