### PR TITLE
Update query-github-for-new-tickets.js

### PR DESCRIPTION
**Pull request by mcourtot**
modified created and updated parameters for date range restriction

### CODE REVIEW

**Comment by mcourtot** [comment]
@kltm first check still fail for qualify, seemingly due to db-xref:
The command "kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0" exited with 1.

Any idea?

**Comment by kltm** [comment]
Is this branch from _before_ my quote fix?

**Comment by mcourtot** [comment]
Would the PR be a *complete* branch copy? I thought it'd be only the modified file... I closed and reopened the PR to retrigger the build but then I guess I need to merge the new db-xrefs back in that branch... Would updating the branch do the trick?

**Comment by kltm** [comment]
That's SVN talk there.
In Git, a commit/tag/whatever, is an entire tree at a point in time.
You'd probably have to merge master to get the changes. Or destroy and redo.

**Pull request closed without merging**
