### PR TITLE
unzipped ttl no longer deleted. Adding JAVA_OPTS for blazegraph-runner environment

### PR DESCRIPTION
**Pull request by dougli1sqrd**
For https://github.com/geneontology/go-site/issues/672

### CODE REVIEW

**Comment by kltm** [comment]
I'm not quite understanding the removal of BGMEM in favor of JAVA_OPTS?

**Comment by dougli1sqrd** [comment]
BGMEM doesn't go to anything. And you provide JAVA_OPTS in the Jenkinsfile.

**Comment by kltm** [comment]
That's "doesn't go to anything" as in `BG` is not used?

**Comment by kltm** [comment]
Cheers! Let's see...

**Pull request merged**
