### PR TITLE
Update groups.yaml

### PR DESCRIPTION
**Pull request by suzialeksander**
adding NCBI for https://github.com/geneontology/helpdesk/issues/291, but can someone confirm we need this groups.yaml entry if they aren't asking for Noctua access? This pull is paired with https://github.com/geneontology/go-site/pull/1595 users.yaml update.

### CODE REVIEW

**Comment by pgaudet** [comment]
I dont know what are our rules for groups - @kltm @cmungall can you provide guidance ? 
We should also document this somewhere.

**Comment by kltm** [comment]
@suzialeksander For the other PR to pass, this would probably need to be over there.
You do not need groups or authorization for a non-noctua user.

**Comment by kltm** [comment]
@suzialeksander Is this still open?

**Comment by suzialeksander** [comment]
I'm going to kill this request, it wasn't entirely clear this user is Noctua-ing and if they haven't run into a problem yet they clearly don't need this.  Can always add again later if we have a problem .

**Pull request closed without merging**
