### PR TITLE
Issue 2093 metadata

### PR DESCRIPTION
**Pull request by mugitty**
Updated to generate aggregate gorule document

### CODE REVIEW

**Comment by dustine32** [comment]
Noting this is tied to a [change](https://github.com/geneontology/pipeline/compare/issue-go-site-2093-metadata#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8L855-R856) in pipeline Jenkinsfile. @mugitty Once this change is made into a pipeline repo PR against `master` it should be referenced to this go-site repo PR.

**Comment by kltm** [comment]
I'll let others decide the merge timing, but I'm happy as long as this goes in before https://github.com/geneontology/pipeline/pull/347

**Review by dustine32 — APPROVED** [review]
@kltm @mugitty Sounds like we're all good with the hard-coding?

Note this PR should be merged before merging https://github.com/geneontology/pipeline/pull/347.

**Comment by kltm** [comment]
Hard-coding is fine, as long as we get the order/timing correct.

**Pull request merged**
