### PR TITLE
Add in ZFIN specific meta data for ZFIN noctua imports

### PR DESCRIPTION
**Pull request by sierra-moxon**

### CODE REVIEW

**Comment by kltm** [comment]
@sierra-moxon Positively confirming that there was no go-site/pipeline changes associated with this?

**Comment by sierra-moxon** [comment]
I did keep go-site/pipeline/requirements.txt up to date with the ontobio releases, but otherwise no.  No changes to this directory.

**Review by kltm — APPROVED** [review]

**Comment by kltm** [comment]
Okay, seems ready for Thursday to me.

**Comment by kltm** [comment]
Looks good to me.

**Pull request merged**
