### PR TITLE
Update users.yaml

### PR DESCRIPTION
**Pull request by vanaukenk**
Adding groups for Birgit, Livia, Helen, and Giulia.  Updating orcids for WB.

### CODE REVIEW

**Comment by kltm** [comment]
Hm, we now have both `http` and `https` URIs in the YAML. @cmungall Any thoughts on this?

**Comment by vanaukenk** [comment]
Hi @kltm and @cmungall 
Any thoughts on the http vs https?
I can change the orcid entries back to http, if https is a problem.

**Comment by kltm** [comment]
@vanaukenk Currently, all 150 are `http` and that's is what will be in all downstream files. My druthers at this point would be `http`.

**Comment by kltm** [comment]
I can fix this inline if you'd don't have time today.

**Comment by vanaukenk** [comment]
One thought, though.  The https actually came in via cut-and-paste from orcid.org, so if someone else populates that field via cut-and-paste, they may also wind up with https and maybe wouldn't know to fix it.  Does https cause problems elsewhere?

**Comment by kltm** [comment]
Currently, they are different IDs in all downstream data.
If we update, we either have to update all models to date or accept that people will have different IDs for a while.
As we are a little short on time, I'd actually be fine with http and https mixed as long as nobody changes.

**Comment by vanaukenk** [comment]
Ah, I see.  So if all my GO-CAM models currently use http and I update my URI to now be https, then will the attribution of my annotations to WB in the GPAD still work?  If not, then yes, we should return all the WB curator entries back to http.

**Comment by kltm** [comment]
They will work, but there will be two different IDs, which may make reporting difficult.
For the moment, my suggested course of action would be: have stable IDs, regardless. For people who already have ORCIDs listed, they should not change to use `https`. For new people, either is fine as long as they do not change later on until we mass migrate everybody over to `https`.

**Comment by kltm** [comment]
It looks like the only remaining changes would be the four group additions and adding a URI for GOC:dr. If that's the case, a new PR may be easier.

**Comment by vanaukenk** [comment]
Okay; will do.  Thx for your input on this one.

**Comment by kltm** [comment]
My apologies for the back and forth and trouble on this one while we worked out what makes the most sense over here.

**Pull request closed without merging**
