### PR TITLE
Deprecate GO_REF Markdown files and replace with YAML file

### LINKED ISSUE #2233: Make `gorefs.yaml` the source of truth instead of Markdown files
To be done after #2232.

- [ ] Run the Markdown-to-YAML script _for the last time_. Move the updated `gorefs.yaml` file up one level to be a direct child of the `metadata` directory alongside other metadata YAML files. This file should now be treated as the source of truth and not the Markdown files.
- [ ] Move the associated LinkML schema up to the `metadata` directory and rename it `gorefs.schema.yaml` to align with existing metadata schema files.

### LINKED ISSUE #2234: Add validation of `gorefs.yaml` to QC workflow
To be done after #2233 

The [QC workflow](https://github.com/geneontology/go-site/blob/master/.github/workflows/qc.yml) already validates a number of metadata YAML files. This task is to add a step to that workflow which validates the `gorefs.yaml` file using its LinkML schema. We should leverage the `linkml-validate` command directly instead of relying on artifacts derived from the LinkML schema.

### PR DESCRIPTION
**Pull request by pkalita-lbl**
Fixes #2233 
Fixes #2234 

### Summary

These changes deprecate the GO_REF Markdown files in favor of the single `metadata/gorefs.yaml` file. 

### Details

* The `gorefs.yaml` file was previously in the `metadata/gorefs` subdirectory. It has been moved up to the main `metadata` directory. The contents have been replaced with the updated format agreed upon in #2232. 
* The LinkML schema describing the new format has been moved up from `metadata/gorefs/linkml-schema` and placed into the main `metadata` directory. It has also been renamed `gorefs.schema.yaml` to align with other metadata schema files.
* The `qc.yaml` workflow file has been updated to use the `linkml-validate` command to test the format of `gorefs.yaml` against the schema.
* Various `README`s updated to indicate that future edits should go to the YAML file and describe the contents of the file.
* Remove extraneous, unused artifacts derived from the LinkML schema

### CODE REVIEW

**Review by kltm — COMMENTED** [review]
Okay, looking through everything seems to make sense, although I will need to send kwalify flowers.

That said, the title made me pause. To clarify, this is getting ready for the cutover but not intended to be the cutover itself, correct?

**Comment by pkalita-lbl** [comment]
It's a... soft cutover? I guess I don't really _intend_ to run the Markdown-to-YAML script again (it gets you like 95% of the way there but I did do some manual formatting to make the resulting YAML more human-friendly). I would hope that if edits need to be made in the short-term (i.e. until this project wraps up) either:

* The edit is only made to the YAML file and it's okay that the "public" release of that edit will be delayed until https://github.com/geneontology/go-site/issues/2235 is done. Or,
* The edit is made to both the YAML file _and_ the Markdown file _if_ it's important that the official (for now) public artifact (the Markdown file) reflects the change (again, until the page on `geneontology.io` becomes the official public artifact in a later issue)

If someone _only_ edits the Markdown file, well, such is life, and I'll try to take responsibility for propagating the change back into the YAML file. But I will grumble about it a little.

**Comment by kltm** [comment]
@pkalita-lbl If you're willing to do some of the grumbling upfront, it might be easiest to just proceed. I'm asking as I know that some GO_REF shuffling is still taking place (e.g. https://github.com/geneontology/gopreprocess/issues/5), but I don't have a feel for how quiet it will be as you proceed. It may be easiest to just compare the directories from https://github.com/geneontology/go-site/commit/394b332a699ef56a554eddaef982a9e6a9df1046 to when this is all done, and catch up manually.

**Comment by pkalita-lbl** [comment]
> It may be easiest to just compare the directories from https://github.com/geneontology/go-site/commit/394b332a699ef56a554eddaef982a9e6a9df1046 to when this is all done, and catch up manually.

Yes I think that's right. If it's just updating the title and description of one reference that's not cause for much grumbling. And I'll try to keep the ball rolling on this project so that there's less opportunity for divergence.

**Review by kltm — APPROVED** [review]
The changes make sense for changing SoT and flow change. We'll circle back around when closer to done to sync.

@pkalita-lbl Feel free to merge on your timing.

**Comment by kltm** [comment]
@pkalita-lbl Okay, looks good.

That said, how "live" is this? Should we direct people to just go for the new SoT, or is the old workflow still "supported" (i.e. the md edits produce changes to the README.md)?

**Comment by pkalita-lbl** [comment]
The old workflow is still very much in place. I didn't touch any of the infrastructure to build the README.md from the Markdown files. I won't remove that until everything else is in place. 

I guess the title of this PR is a bit overreaching. We'll be in a split source-of-truth situation for a little while. The most helpful thing people could do during this time is make updates to both the Markdown files _and_ the YAML file. But if someone misses the YAML file, as previously noted, we'll sync it back up before we close out the project and fully ditch the Markdown files.

**Comment by kltm** [comment]
Okay, all good--merge at your convenience.

**Pull request merged**
