### PR TITLE
adding ontobio gaf parsing to instead of mikes script

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
Should we make a ticket for that in ontobio?

**Comment by cmungall** [comment]
+1

**Comment by dougli1sqrd** [comment]
Since ontobio is updated, we probably need another release. Then go-site can depend on the newest version with --filter-out and this can be merged

**Comment by cmungall** [comment]
looks good

**Pull request merged**
