### PR TITLE
Added GRIN database xref stanza

### PR DESCRIPTION
**Pull request by austinmeier**

### CODE REVIEW

**Comment by kltm** [comment]
@austinmeier As a whole, it looks like this PR is failing the tests. You might want to try the tests locally before resubmitting.

**Comment by cmungall** [comment]
No need. @austinmeier just click on the X above to see the travis report (you have probably trawled through some of these for ontology checks).

Normally this will show the source of your error...

HOWEVER, something is odd here, and it may not be your fault. The travis report says:

```
ERROR: metadata/users.yaml:278:43 [/] document end expected (maybe invalid tab char found).
```

However, you didn't touch users.yaml...

**Comment by kltm** [comment]
See issue #131.

**Comment by cmungall** [comment]
OK, I'll reopen to see if we can get more informative output

**Comment by kltm** [comment]
Should dump all relevant output now--will close and reopen (causing travis re-run, thanks @cmungall).

**Comment by kltm** [comment]
The failure is a uniqueness violation and cannot be merged:
```
metadata/db-xrefs.yaml:2722:3 [/262/database] 'ISBN': is already used at '/106/database'.
```

**Pull request closed without merging**
