### PR TITLE
Update users.yaml

### PR DESCRIPTION
**Pull request by hdrabkin**
adding info for past MGI editors : Teresa Chu, Tony Planchart (add orc id), and Alan P Davis

### CODE REVIEW

**Comment by hdrabkin** [comment]
@kltm help! error is "    ^
expected <block end>, but found '<block sequence start>'
  in "<unicode string>", line 4016, column 2:"

I didn't touch line 4016!

**Comment by hdrabkin** [comment]
@kltm : found all errors but could you look at this? If looks ok, please merge

**Comment by kltm** [comment]
@hdrabkin Will do~!

**Comment by kltm** [comment]
Looks fine to me, the the proof is in the pudding--let's merge and see.

**Pull request merged**
