### PR TITLE
Created new gorule-0000041

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by kltm** [comment]
This appears to be the same as GO Rule 11, which can be reworded as one-to-one and onto.

**Comment by pgaudet** [comment]
No, it's the reverse of Rule 11. I think we need both.

**Comment by dougli1sqrd** [comment]
Why can we not have gorule-11 say something like:
```
annotations to the GO roots can only have ND evidence, and ND evidence can only used with annotations to the Go roots.
```

Like, this is a one to one mapping between the two ideas, being the ND evidence code and the GO roots.

**Comment by pgaudet** [comment]
OK

**Pull request closed without merging**
