### PR TITLE
update to use regenerated ontobio package

### PR DESCRIPTION
**Pull request by sierra-moxon**
I can run RGD, MGI, CGD, goa-cow all locally via the tests in ontobio, and via the makefile command here in pipeline.  can we give this a shot on snapshot?

### CODE REVIEW

**Comment by kltm** [comment]
@sierra-moxon Great news!
I want to hold off briefly, while I complete the current release. We can move forward v/early next week?

**Review by kltm — COMMENTED** [review]
Bump.

**Comment by sierra-moxon** [comment]
makes sense to wait; np.

**Comment by kltm** [comment]
@sierra-moxon The `release` is cleared and you are free to merge. Is this the one we're testing?

**Pull request merged**
