### PR TITLE
Update users.yaml

### PR DESCRIPTION
**Pull request by srengel**
added "groups:
  - 'http://www.yeastgenome.org'"

for current SGD curators: Edith, Rob, Marek, Sage, Kevin, Emily, Terry, Stacia, Olivia

### CODE REVIEW

**Comment by kltm** [comment]
@srengel What you are inputting is not consistently YAML. If you look at the differences between what you added between Rob and Edith, Edith is correct.

**Comment by srengel** [comment]
oops will try to fix…

On Jun 27, 2017, at 1:24 PM, kltm <notifications@github.com<mailto:notifications@github.com>> wrote:


@srengel<https://github.com/srengel> What you are inputting is not consistently YAML. If you look at the differences between what you added between Rob and Edith, Edith is correct.

**Comment by kltm** [comment]
I assume that your `patch-3` was just a redo of this one?

**Comment by srengel** [comment]
yes, that was all me trying to get this done correctly.  ugh.  thanks for fixing my mistakes.  i'm out of the file now and don't plan to get back in :)

**Pull request closed without merging**
