### PR TITLE
update ontobio to 1.17.4

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
I'll merge once travis passes.

**Comment by kltm** [comment]
@dougli1sqrd Apologies, my internet is sudden v/slow and I did not see that. And it looks like it didn't pass. Want me to revert?

**Comment by dougli1sqrd** [comment]
I'll look at the logs first. Could be a travis hiccup.

**Comment by kltm** [comment]
@dougli1sqrd It looks from the failure that a release has not been made (or is live)?

**Comment by dougli1sqrd** [comment]
The other travis check passed, so I think a re-run should pick up the new ontobio

**Pull request merged**
