### PR TITLE
Added TFClass as a dbxref [BUILD FAILING]

### PR DESCRIPTION
**Pull request by pgaudet**
For NTNU annotations

### CODE REVIEW

**Comment by pgaudet** [comment]
@cmungall @kltm @dougli1sqrd Any idea why this is failing ?

**Comment by cmungall** [comment]
@dougli1sqrd can you look into this, this is sparta. [said in Gerard Butler voice]

Looks like some upstream dependencies changed, should we not have a docker container for this?

**Comment by dougli1sqrd** [comment]
I don't think this...is...sparta!!

I'm seeing in the travis logs:
```
0.24s$ kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
metadata/db-xrefs.yaml#0: INVALID
metadata/db-xrefs.yaml:3424:3 [/324/generic_urls] 'http://tfclass.bioinf.med.uni-goettingen.de/': not a sequence.
metadata/db-xrefs.yaml:3430:7 [/324/entity_types/0/url_example] key 'url_example:' is undefined.
metadata/db-xrefs.yaml#0: INVALID
The command "kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0" exited with 1.
```
so the value for `generic_urls` should be a sequence, not a string (see other examples above the change)

**Comment by pgaudet** [comment]
Thanks @dougli1sqrd

**Pull request merged**
