### PR TITLE
made github account a first-class parameter

### PR DESCRIPTION
**Pull request by nathandunn**
Not sure if you still need accounts @kltm , but this is the right change to fix https://github.com/geneontology/termgenie/issues/98 with other fixes.

### CODE REVIEW

**Comment by cmungall** [comment]
I don't understand what you're doing here, is this an agreed upon change to the schema? We need to decide whether github and other accounts are top level or not. But it shouldn't be in both places.

**Comment by nathandunn** [comment]
Definitely doesn't need to be in both places but I don't know the history of the schema.  Was just trying to quickly fix the termgenie code.  However, if you think that this will violate it, I can definitely work around it.  Just let me know.  

Nathan

**Comment by cmungall** [comment]
well it's already violating the schema, hence the travis err

I think the code will have to be fixed to do the lookup in the accounts object

**Comment by nathandunn** [comment]
No problem.  Please close it then. 

Nathan

**Comment by nathandunn** [comment]
Talked to @cmungall  and decided not to do it this way.

**Pull request closed without merging**
