### PR TITLE
Adding groups for UCL, MGI, RGD

### PR DESCRIPTION
**Pull request by cmungall**
Question: @RLovering do we have a full URL for BHF project

### CODE REVIEW

**Comment by RLovering** [comment]
Dear Chris
please could you create a variety of options for me and my team as we work on different projects with different funding. I was delaying sorting this out until Tony confirmed that I could use the names as they appear in QuickGO

So the group lists are (group_name URL) :
3 options for Ruth Lovering:
BHF-UCL https://www.ucl.ac.uk/functional-gene-annotation/cardiovascular 
ARUK https://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/aruk-ucl/
SynGO-UCL https://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/syngo-ucl/

2 options for Barbara Kramarz:
ARUK https://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/aruk-ucl/
SynGO-UCL https://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/syngo-ucl/

1 option for Rachael Huntley:
BHF-UCL https://www.ucl.ac.uk/functional-gene-annotation/cardiovascular 

Is this possible?

Thanks

Ruth

**Comment by cmungall** [comment]
OK, we already added the groups:

https://github.com/geneontology/go-site/blob/master/metadata/groups.yaml#L27-L34

Barbara:
https://github.com/geneontology/go-site/blob/master/metadata/users.yaml#L2995-L2997

Just added Rachael now:
https://github.com/geneontology/go-site/pull/378

**Comment by RLovering** [comment]
Hi Chris

I can’t see an arrow next to my name that would enable me to select my different identities, but maybe you didn’t realise I was hoping to get identity options too?

Or maybe it takes a while for this to be live
Best

Ruth

**Comment by kltm** [comment]
I've just done an update--would you mind giving it another try?

**Comment by RLovering** [comment]
Hi there, sorry still no luck. Barbara has shown me how she sees this but I just have my name. Maybe the yaml file needs tweeking?

Thanks

Ruth

**Comment by kltm** [comment]
@RLovering 
Um...looking at  https://github.com/geneontology/go-site/blob/master/metadata/users.yaml#L253 , you have no groups listed. Compare with: https://github.com/geneontology/go-site/blob/master/metadata/users.yaml#L2983 .

**Comment by cmungall** [comment]
My fault, I responded to Ruth above saying I had added everyone when in fact I hadn't.

**Pull request merged**
