### PR TITLE
sparql impl of gorule 7

### PR DESCRIPTION
**Pull request by dougli1sqrd**
Paging @balhoff for advice also, but I can't add him as a reviewer

### CODE REVIEW

**Comment by cmungall** [comment]
minor: let's use uppercase 'GO' as the prefix. Semantically identical but good to be consistent.

**Comment by balhoff** [comment]
@cmungall not sure how you feel about this but these can be even more readable by putting all the IDs in the prefixes:

```sparql
PREFIX CatalyticActivityMolecularFunction: <http://purl.obolibrary.org/obo/GO_0003824> 
# elided...
?j a CatalyticActivityMolecularFunction: . 
```

**Comment by cmungall** [comment]
+1, I use this pattern a lot. And I usually separate with underscores 
and retain source capitalization, rather than CamelCasing

**Comment by dougli1sqrd** [comment]
@balhoff @cmungall I can update the prefixes in this way. Should I change all the prefixes to be all caps?

**Comment by balhoff** [comment]
I would not make it all caps in the cases where you're putting a whole readable name in. For example, both of these are good:

```sparql
PREFIX GO: <http://purl.obolibrary.org/obo/GO_>
PREFIX catalytic_activity: <http://purl.obolibrary.org/obo/GO_0003824>
```

For `GO:`, you would be appending the number in the query body, like `GO:0003824`. For `catalytic_activity:`, you would just use it as a placeholder by itself.

**Pull request merged**
