### PR TITLE
Added example

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by pgaudet** [comment]
This is still failing - @kltm can we look at this together to explain what I need to do next ?

**Comment by kltm** [comment]
@dougli1sqrd Could you link this with the other ticket and/or help Pascale create a new high-level ticket?

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/issues/400

**Comment by dougli1sqrd** [comment]
@pgaudet the example checker code has been updated. So it looks like your GAF lines as examples in fact do not have enough columns, so they aren't proper gafs.

**Comment by kltm** [comment]
Talked to @pgaudet , throwing this out

**Pull request closed without merging**
