### PR TITLE
Updating db-xrefs.yaml for issue #765 - fix TAIR:locus ID validation …

### PR DESCRIPTION
**Pull request by dustine32**
…errors

### CODE REVIEW

**Comment by kltm** [comment]
@dustine32 Could you hold off on this for a minute...

**Comment by kltm** [comment]
Well, this should break any of our stuff, as it's dumber. @tonysawfordebi Does this work for you and your smarter stuff?

**Comment by tonysawfordebi** [comment]
@kltm Sorry for the delayed reply - was away last week

The proposed changes to eco-usage-constraints.yaml look good to me, so I say ship it...

**Comment by tonysawfordebi** [comment]
I had forgotten one thing...

We need one more update in order to make all our validation stuff work correctly, and that is to add this entry for SO:0000185 into go-upper.obo:

[Term]
id: SO:0000185 ! primary_transcript
name: primary_transcript
is_a: SO:0000673 ! transcript

(see https://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0000185)

There is already an entry for SO:0000673 in go-upper.obo

**Comment by tonysawfordebi** [comment]
I've updated go-upper.obo
(https://github.com/geneontology/go-ontology/pull/16284)

**Comment by tonysawfordebi** [comment]
@kltm Any idea how long it will take for the changes that I made yesterday to find their way into http://snapshot.geneontology.org/ontology/extensions/go-upper.obo?

**Comment by tonysawfordebi** [comment]
Thanks - it looks like everything's in place now.

**Comment by dustine32** [comment]
Thanks @tonysawfordebi for fixing this!

**Pull request merged**
