### PR TITLE
Ensure model deletion query is not sensitive to string datatype

### PR DESCRIPTION
**Pull request by balhoff**
See https://github.com/geneontology/noctua/issues/736

### CODE REVIEW

**Comment by balhoff** [comment]
@kltm can we test this in a pipeline run?

**Comment by kltm** [comment]
@balhoff Depending on stomach for risk, I might just add it to `master` and let it run through naturally. We could even kill `snapshot` right now and restart it immediately.

**Comment by balhoff** [comment]
I feel confident, go with either of those.

**Comment by kltm** [comment]
@balhoff Okay, I'm going to 1) merge, 2) stop current `snapshot`, and 3) immediately start a new `snapshot` so we can see full products (which would maybe be available starting this time tomorrow or a little after, depending if anything else goes "boink").

**Pull request merged**
