### PR TITLE
Update users.yaml

### PR DESCRIPTION
**Pull request by suzialeksander**
Editing as per @zebrafishembryo 's request through helpdesk.  I think groups and organization are optional fields, and previous-groups is in the schema although I don't see use of  previous-groups anywhere else in this yaml??

### CODE REVIEW

**Comment by kltm** [comment]
@suzialeksander While not in the schema, there is a secondary sanity check (`python3 ./scripts/sanity-check-users-and-groups.py --verbose --users metadata/users.yaml --groups metadata/groups.yaml`) which requires users to have a group. We put that in there for a reason (probably); I'm trying to think why we do that...

**Comment by kltm** [comment]
@suzialeksander Okay, looking at the code a little, I think I know what we're doing and why it's failing. As a general rule, the entries in users.yaml do not require a group, etc., so it is not in the schema. However, as a matter of GO/Noctua policy, it was decided some time ago that groups were required for noctua editors (as opposed to other entries); as part of enforcing that policy, this script was added.
If we want to revisit that, we should probably do that formally--that assumption may be bolted in other places now.

**Comment by kltm** [comment]
I'd also note that something in "groups" can be quite informal and trivial, not necessarily something as large as a MOD or other resource.

**Comment by suzialeksander** [comment]
@vanaukenk can we get an "official" Noctua approval for this change?

**Comment by suzialeksander** [comment]
I've added GOC as Alice's `group`, as I think we discussed.  Can @kltm and @vanaukenk verify this is ok, and ok to merge?

**Comment by vanaukenk** [comment]
@suzialeksander - this is a question for @thomaspd 
Let's confirm with him first (unless you've already heard from him).

**Comment by suzialeksander** [comment]
Sounds like GOC is the solution for now. @kltm ok to merge?

**Comment by kltm** [comment]
Sounds good. Discussed with @vanaukenk and @pgaudet

**Pull request merged**
