### PR TITLE
Update users.yaml

### PR DESCRIPTION
**Pull request by suzialeksander**
adding noctua permissions for Noctua display as mentioned in https://github.com/geneontology/go-site/issues/2228

### CODE REVIEW

**Comment by suzialeksander** [comment]
apparently the sheriff alerted.  will try again.

**Comment by kltm** [comment]
@suzialeksander Noting from the errors:
```
ERROR:sanity:Anand Sethuraman "uri" is not an ORCID.
ERROR:sanity:Cathy Ball "uri" is not an ORCID.
ERROR:sanity:Cindy Krieger "uri" is not an ORCID.
ERROR:sanity:Julie Park "uri" is not an ORCID.
```

**Comment by suzialeksander** [comment]
Correct. I posted in the discussion on https://github.com/geneontology/go-site/issues/2228  that we don't have ORCIDs for at least one of them, not sure the solution.

**Comment by suzialeksander** [comment]
@kltm I don't have ORCIDs and you pointed out that `GOC:`IDs will technically work here.  OK to merge?

**Comment by kltm** [comment]
No: no merging can occur when there are errors. If you added this anyways, all future PRs would also fail, rendering the tests unusable.
```
ERROR:sanity:Anand Sethuraman "uri" is not an ORCID.
ERROR:sanity:Cathy Ball "uri" is not an ORCID.
ERROR:sanity:Cindy Krieger "uri" is not an ORCID.
ERROR:sanity:Julie Park "uri" is not an ORCID.
REPAIR?: Revoke Anand Sethuraman noctua-go edit privileges.
REPAIR?: Revoke Cathy Ball noctua-go edit privileges.
REPAIR?: Revoke Cindy Krieger noctua-go edit privileges.
REPAIR?: Revoke Julie Park noctua-go edit privileges.

No URI, or no ORCID:
===================
Cathy Ball
Cindy Krieger
Julie Park
Anand Sethuraman
```
This means that a test fix will either have to be applied or some other change to the data.

**Review by kltm — CHANGES_REQUESTED** [review]
Tests will need to pass

**Comment by suzialeksander** [comment]
OK, i removed the edit privileges, these are users no longer active anyway. Does it look ok now?

**Review by kltm — APPROVED** [review]

**Pull request merged**
