### PR TITLE
Update users.yaml

### PR DESCRIPTION
**Pull request by tberardini**
Trying again.  Merged 2 records for Leonore.

### CODE REVIEW

**Comment by tberardini** [comment]
Clearly I don't know what I'm doing.   I don't know why this failed.

**Comment by kltm** [comment]
I looks like you duplicated half the stanza here:
https://github.com/tberardini/go-site/blob/4338d5d7b4a03a80d20496681546057312351035/metadata/users.yaml#L1369
The error is a little unclear, but you have two email-md5s, two organizations, etc.

**Comment by kltm** [comment]
I've made the merge for Lenore on master separately. Check to make sure this is what you want, modify as you see fit:
https://github.com/geneontology/go-site/commit/9f1ddd73635671f6815330c405490ec4255f9c4c

**Comment by ukemi** [comment]
I think that is a brilliant idea!

**Comment by cmungall** [comment]
genius. I'm on it.

**Pull request closed without merging**
