### PR TITLE
Update zfin.yaml

### PR DESCRIPTION
**Pull request by sabrinatoro**
A gpi file is now available for ZFIN. I have added the information for this file.

### CODE REVIEW

**Comment by kltm** [comment]
@sabrinatoro 
I had a question about this. In the file, you have `compression: gzip`, but the source is not compressed, and there appears to not be a compressed file on the server. Is there a plan to gzip the GPI?

**Comment by sabrinatoro** [comment]
@kltm : You are right, the source is not compressed (my mistake). 
At this point, there is no plan to gzpi the GPI . So the yaml file should be update to compression: none? (or should I add nothing? remove that line?). 

However, if it is better to have a gzip format, I can ask the devs to update the file.

**Comment by kltm** [comment]
@sabrinatoro 
If there is no intention to compress, the line would just be removed completely. I believe that the compressed versions have been fairly standard in the case of GAFs, so I'd assume this tradition would have utility; if there is not much additional burden, it might be good to add.
Pinging @cmungall in case he wants to chime in here.

**Comment by sabrinatoro** [comment]
OK, I will remove the line about the compression, and will add it back when we get a compressed file.

**Comment by kltm** [comment]
Cheers!

**Comment by cmungall** [comment]
Look ok now? (at top of this page look at "Files changed"), thanks!

**Comment by kltm** [comment]
@sabrinatoro Is this closable now?

**Comment by sabrinatoro** [comment]
yes, I think we can close. Thanks

**Pull request closed without merging**
