### PR TITLE
Hackathon 2020 rules

### PR DESCRIPTION
**Pull request by dougli1sqrd**
This is the work from the January Hackathon with @dustine32  and built upon since then. This mostly defines the two new rules we will be using in import.

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
This is now ready to merge.

**Comment by kltm** [comment]
@dougli1sqrd It seems that the constraints TSV is being added here, instead of the preferred JSON?

**Comment by dustine32** [comment]
@kltm The [JSON](https://github.com/geneontology/go-site/pull/1398/files#diff-3eb73beb831db23a37f3d1391d752bcc) is also added but hidden by the "large data don't display" shield. I don't think the TSV is actually used.

**Comment by kltm** [comment]
@dustine32 Mind if I pull it from the PR then? We don't want to have two (possibly confusing) sources for the same info floating around.

**Comment by dustine32** [comment]
@kltm Sure, I think pulling it should be fine.

**Comment by dougli1sqrd** [comment]
@kltm @dustine32 just to confirm, we are keeping the YAML extensions-constraints, and removing the TSV?

I approve of that.

**Comment by kltm** [comment]
So say we all.

I'm not sure if this is ready to go into master or not, but what I've seen makes sense and I'm fine with a merge if that's the desire (and I'll leave it to youseall).

**Comment by dustine32** [comment]
Yep @dougli1sqrd correct! Keep the YAML (der! i keep thinking it's a JSON) and trash the TSV.

**Comment by dougli1sqrd** [comment]
http://skyhook.berkeleybop.org/go-site-pr-1398-hackathon/reports/gorule-report.html

Pipeline finished which is good, but I feel like the new rules, rule 57 and 58, should not be run yet. Ontobio should not be running any import rules unless the import context is passed in, but here we are. So it looks like ontobio is actually misbehaving somehow.

I'll take a look.

**Comment by kltm** [comment]
Half glass full!

**Comment by dougli1sqrd** [comment]
Okay the new reports look better! http://skyhook.berkeleybop.org/go-site-pr-1398-hackathon/reports/gorule-report.html

57 and 58 are not running in a standard run of the pipeline.

**Comment by kltm** [comment]
Is this to be merged then, or still working?

**Comment by pgaudet** [comment]
Looks like it's still in progress ? Only some species are shown.

**Comment by dougli1sqrd** [comment]
Yeah this is safely mergable at this point.

**Pull request merged**
