### PR TITLE
adding _noiea to the dataset value in goa rna datasets

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by kltm** [comment]
As discussed in #1168 , we will be backing out of this.

**Comment by kltm** [comment]
Will reuse.

**Comment by dougli1sqrd** [comment]
Okay new commit. @kltm is this putting back the original IDs. Can you double check the `url` field to make sure that is correct?

**Comment by kltm** [comment]
This looks fine to my eye.
As far as the `url` field goes...it's technically not up to date. See: https://github.com/geneontology/go-site/blob/b039a4b613d135f3f8a578f6adc5363b8cc9b69d/metadata/datasets/dictybase.yaml#L50
That said, I can't recall off the top of my head why we haven't updated these. Perhaps an oversight? Any thoughts @pgaudet ?
If this is what was historically in there, let's just go with that.

**Comment by kltm** [comment]
@pgaudet Okay, this is weird; I'm going to reopen #804

**Pull request merged**
