### PR TITLE
Updated EC links

### PR DESCRIPTION
**Pull request by pgaudet**
@kltm Are we allowed to put more than one URL example? It's nice to know how to construct partial links. (We have many links missing the 'dash' in the ontology- but that's another issue).

### CODE REVIEW

**Comment by kltm** [comment]
@pgaudet 
https://www.expasy.org/EC/1.4.3.6
https://www.expasy.org/EC/1.4.3.-
Are not legal URLs. What is your intention with the PR? The syntax and examples are now different.

**Comment by kltm** [comment]
examples are singular in the schema:
https://github.com/geneontology/go-site/blob/b1694ab5de6edfc0b3d4fada97cc5f9b366f508c/metadata/db-xrefs.schema.yaml#L57

**Comment by pgaudet** [comment]
Thanks for the feedback @kltm

**Comment by kltm** [comment]
@pgaudet Could you please make it so the example URL and the URL giving the syntax are of the same format? As it stands now, the testing URL cannot be generated from the syntax URL.

**Pull request merged**
