### PR TITLE
Created new gorule-0000046

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by kltm** [comment]
Talked with @dougli1sqrd and this will need more of a description before it can be implemented. To clarify, is this about GO:0043621? So, if has said term in closure, with/from must not be empty and must be topic protein?

**Comment by pgaudet** [comment]
@tonysawfordebi Which terms do you test for this in P2GO ? 
GO:0043621 is 'self-association', meaning associating with the same molecule; it seems wrong to have two entities in this case - I would even say GO:0043621  should NOT have anything in the 'with' field.

**Comment by RLovering** [comment]
But as we are exporting data from the with field to PSICQUIC then it might be useful for people to see self-binding annotations in their networks, plus the evidence for selfassociation is IPI and with themselves.
Ruth

**Comment by pgaudet** [comment]
Let's implement this rule the same way as P2GO. I guess that means GO:0043621 is also included. 

@tonysawfordebi @alexsign Is this right ?

**Comment by alexsign** [comment]
@pgaudet  Tony is away this week, he can clarify it when he is back next week. But, from what I can see from protein2go check is if the GO term is GO:0043621 (protein self-association), GO:0042803 (protein homodimerization activity) or GO:0042802 (identical protein binding), then standalone IPI annotations are allowed

**Comment by pgaudet** [comment]
'Standalone' meaning without 'with' info ?

**Comment by alexsign** [comment]
No, in this case, as I understand it, you don't have to create Reciprocal Annotation

**Comment by pgaudet** [comment]
OK, thanks

**Comment by alexsign** [comment]
I'm looking at the protein2go code now. I find another rule which basically: if it's self-binding term annotation, with_string and entity must be the same. If I find more rules related I'll post it here as well.

**Comment by pgaudet** [comment]
@alexsign I suppose the same rule applies to IGI ?

**Comment by alexsign** [comment]
@pgaudet  I don't see the same rules implemented in the code for IGI.

**Pull request merged**
