### PR TITLE
Update db-xrefs.yaml

### PR DESCRIPTION
**Pull request by krchristie**
I need to be able to refer to a term from the Brenda tissue / enzyme source for a term I added based on this request:
https://github.com/geneontology/go-ontology/issues/15616

### CODE REVIEW

**Comment by krchristie** [comment]
@cmungall - I never saw where I was supposed to tag you as a reviewer, and I don't seem to be able to add you now either.

This is the entry I was proposing to add, based on the ontology issue ticket I referred to above.

- database: BTO
  name: BRENDA tissue / enzyme source
  description: A structured controlled vocabulary for the source of an enzyme comprising tissues, cell lines, cell types and cell cultures.
  rdf_uri_prefix: http://purl.obolibrary.org/obo/BTO_
  generic_urls:
    - http://purl.obolibrary.org/obo/bto
  entity_types:
    - type_name: entity
      type_id: BET:0000000
      url_syntax: http://purl.obolibrary.org/obo/BTO_[example_id]
      example_id: BTO_0002164
      example_url: http://purl.obolibrary.org/obo/BTO_0002164

**Comment by cmungall** [comment]
sorry for the delay

I changed the title to distinguish this from the BRENDA database entry we already have

Curious as to your use case for BTO? is this for a metazoan tissue? or cell line? Other ontologies play better with the GO ecosystem (e.g. uberon/fao/po/cl/clo)

**Comment by kltm** [comment]
Fixing line wrap.

**Comment by krchristie** [comment]
@cmungall - No this is not for a metazoan tissue; it's fungi. Use case is in ticket I linked to in original request.

**Comment by krchristie** [comment]
@cmungall @kltm - It looks like you guys made this change yesterday (5/31). Is this supposed to be available today (6/1), or does it take more time to propagate through? When I try to add the relevant BTO ID as a definition dbxref, I am still getting this error:

 :: ERROR: valid-id-space: bad id space 'BTO' in xref BTO:0002164

**Comment by kltm** [comment]
This PR was not in for the monthly release--it has still not been merged.

**Comment by kltm** [comment]
Once merged, depending on the use case, it will start percolating out.

**Comment by krchristie** [comment]
Can you please tag me once it is merged in so that I know when it is worth trying again to finish the original ontology ticket. Thanks!

**Pull request merged**
