### PR TITLE
Upgrade ontobio to check null with from field

### PR DESCRIPTION
**Pull request by mugitty**
biolink/ontobio#660

### CODE REVIEW

**Comment by mugitty** [comment]
For https://github.com/geneontology/pipeline/issues/346

**Comment by kltm** [comment]
@mugitty Possible failure wrt https://github.com/geneontology/go-site/pull/2194#event-11077176508?

**Comment by kltm** [comment]
Otherwise, happy to have you self-merge after passing.

**Review by kltm — APPROVED** [review]
Otherwise, happy to have you self-merge after passing.

**Comment by kltm** [comment]
@mugitty Still having the sparta error; perhaps you need to merge in your recent changes?

**Pull request merged**
