### PR TITLE
Update gorefs.yaml

### PR DESCRIPTION
**Pull request by pgaudet**
Update GO_REF:0000002

### CODE REVIEW

**Review by pgaudet — COMMENTED** [review]
fixed url

**Comment by pgaudet** [comment]
@pkalita-lbl I dont know how I broke this !

**Comment by pkalita-lbl** [comment]
You're running into one of the ways that YAML is sensitive to whitespace. Specifically, when text is wrapped over multiple lines, those lines need to be indented. In these screenshots, the left show how it is now, and the right shows the correct indentation:

image

It looks like the changes in https://github.com/geneontology/go-site/pull/2314 also ran into this same issue. The sad thing is that GitHub's web editor doesn't really help you out by flagging this kind of issue as you make the changes.

**Comment by pgaudet** [comment]
Thanks @pkalita-lbl that's very useful!

**Pull request merged**
