### PR TITLE
create noctua config yaml

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by kltm** [comment]
@dougli1sqrd Will merging this into master trigger appending the GO-CAM data?

**Comment by dougli1sqrd** [comment]
No. We would still have to release ontobio, and update the versions on go-site. But noctua will be picked up by the pipeline. I'm testing how the pipeline will see noctua as its own group now.

**Comment by dougli1sqrd** [comment]
Adding this won't change anything. This will become a target by the pipeline, but as all sources are gpad, each dataset is skipped. The pipeline currently only accepts gaf primary sources.

**Comment by kltm** [comment]
Fair enough, but should all start as `inactive`, as that will be the initial default as it will be opt-in?

**Comment by dougli1sqrd** [comment]
we currently ignore the `status` field. For documentation purposes we could switch to inactive?

**Comment by kltm** [comment]
@dougli1sqrd Okay to merge if you are okay with my changes.

**Comment by dougli1sqrd** [comment]
Looks good

**Pull request merged**
