### PR TITLE
Added pass/fail examples

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by kltm** [comment]
@pgaudet Noting that your YAML is invalid, at least according to the internal Travis checks.

**Comment by pgaudet** [comment]
Errr, great ??

**Comment by pgaudet** [comment]
Actually it's as if the parser does not know about the interacting taxon column ? 

Error is: 

> Rule example failed: Input was expected to fail gorule-0000015, but it did not: GORULE:0000001: Date field must be YYYYMMDD, got: taxon:9696; GORULE:0000001: Could not parse date 'taxon:9696' at all

But the Interacting Taxon column (Col 13) should come before the date (Col 14)
http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/

Isn't it ? 

Thanks, Pascale

**Comment by kltm** [comment]
@dougli1sqrd Before opening a ticket, I wanted to confirm this oddity:

The input stanza is (looking at second item):

```yaml
  pass:
    - comment: Should pass because "defense response to Gram-positive bacterium" is a child of "GO:0044419 interspecies interaction between organisms"
      format: gaf
      input: "UniProtKB	A0A0B5JW41	cd59		GO:0050830	PMID:23707788	IDA		P	UPAR/Ly6 domain-containing protein	cd59	protein	taxon:7955|taxon:90370	20130923	ZFIN"
    - comment: Should pass because "negative regulation of cytolysis in other organism" is a child of "GO:0043903 regulation of interspecies interactions between organisms"
      format: gaf
      input: "UniProtKB	G3XD78	rsaL		GO:0051713	PMID:19878323	IMP		P	Regulatory protein RsaL	rsaL,PA1431	protein	taxon:208964|taxon:90370	20190311	PseudoCAP"
```

The output is:
```json
        {
            "rule": "gorule-0000015",
            "type": "fail",
            "format": 2,
            "input": "UniProtKB\tG3XD78\trsaL\t\tGO:0051713\tPMID:19878323\tIMP\t\tP\tRegulatory protein RsaL\trsaL,PA1431\tprotein\ttaxon:208964|taxon:90370\t20190311\tPseudoCAP",
            "expected": true,
            "actual": false,
            "success": false,
            "reason": "Input was expected to fail gorule-0000015, but it did not: GORULE:0000015: Dual species taxon check"
        }
```

The question is why the rule test is coding as `fail` instead of `pass`. As a lead, none seem to be `pass`: https://travis-ci.org/github/geneontology/go-site/builds/699057598

**Comment by dougli1sqrd** [comment]
Oh yeah, that does seem definitely strange and not correct. I can't think of a reason off hand, I'd have to look deeper into it.

**Pull request merged**
