### PR TITLE
remove sgd gpi entry

### PR DESCRIPTION
**Pull request by kltm**
Remove confusing GPI entry as a workaround for https://github.com/geneontology/neo/issues/36

### CODE REVIEW

**Comment by kltm** [comment]
@dougli1sqrd If @cmungall is not available, could you confirm this has the desired effect?

**Comment by dougli1sqrd** [comment]
If this passes the schema checker, then this is fine. The pipeline doesn't look at GPI files yet, so this seems all good to me.

**Comment by kltm** [comment]
Hmmm...maybe it's looked at in the NEO assembler. I'll merge and I guess we'll see.

**Comment by cmungall** [comment]
This should have the desired affect, thanks.

https://build.berkeleybop.org/job/build-noctua-entity-ontology/
ran successfully

Connection is too slow to check the file here

We'd expect gene IDs to show up here:

```
$ curl -L -s http://purl.obolibrary.org/obo/go/noctua/neo.owl | grep SGD
```

**Pull request merged**
